### PR TITLE
Please see my changes on AutoCell size

### PR DESCRIPTION
**Pull request by HelioGuilherme66**
AutoCellSize On effect was very similar as when Off. Do we want always to have full cell content readable?
Also did not manage to get long text using the max cell size.

The other changes are with cell navigation with Enter and BackSpace. They go to Right and Left.
Also when we Edit cell content we move Right.
(Need to add this to Shortcut Keys help)

### CODE REVIEW

**Comment by HelioGuilherme66** [comment]
I was not happy with the result, so I did more changes (I am not totally happy with small cells content always getting the default size).
If you agree with them, we should clean up the code for comments.
Thanks!

**Comment by 2Eagle2** [comment]
auto cell off should not adjust row size - so I agree with that.
your last changes make the rows always bigger then they should be
  - in auto on - keywords like Log variables occupy 2 rows without a reason
  - in manual mode - the cell height cannot be shrinked even after the col size is extended

> I am not totally happy with small cells content always getting the default size

what col size do you expect from small cells contents ? should auto col size make the col smaller than default when the content of cell is small ?

**Comment by HelioGuilherme66** [comment]
> auto cell off should not adjust row size - so I agree with that.

Then it should stay `default size`
> your last changes make the rows always bigger then they should be
> 
> * in auto on - keywords like Log variables occupy 2 rows without a reason

That was a difficulty I got, because they are always wordwrapped. My efforts went in not having wrapped to use up to the `maximum size`, but seems it is ignored. (there may be some wxPython settings overriding our code).
> * in manual mode - the cell height cannot be shrinked even after the col size is extended

Looks like the `default size` is acting as minimum size. I don't know why.
Other problem, is, since we don't store the cells sizes (they are always recalculated), when we get back to the grid we lost those settings.
> 
> > I am not totally happy with small cells content always getting the default size
> 
> what col size do you expect from small cells contents ? should auto col size make the col smaller than default when the content of cell is small ?

Yes, this was a behavior, I previously seen. For example if a cell contains only a single digit number, it should use only that small size, plus padding.

**Comment by HelioGuilherme66** [comment]
@2Eagle2 With these final changes, we can select if cells have word wrap or and auto adjusts row height.
Also set a small size if the cells are empty. I think it is good to merge now.
Please merge in your fork, then I'll merge in official project.

**Comment by 2Eagle2** [comment]
Thank you very much :+1: 
I think this is as it should be.
I think that the size of cell should be manually shrinkable but I will let it on separate PR for that.
Lets close this one.

**Pull request merged**
